`define ALUOP_L     5-1:0

`define ALU_PASS    0
`define ALU_ADD     1
`define ALU_ADDC    2
`define ALU_SUB     3
`define ALU_SUBU    4
`define ALU_SUBB    5
`define ALU_INC     6
`define ALU_DEC     7
`define ALU_AND     8
`define ALU_OR      9
`define ALU_NOR     10
`define ALU_XOR     11
`define ALU_SLL     12
`define ALU_SRL     13
`define ALU_SLA     14
`define ALU_SRA     15
`define ALU_SLR     16
`define ALU_SRR     17
`define ALU_SEQ     18
`define ALU_SLT     19
`define ALU_SLTU    20
`define ALU_NEG     21
`define ALU_NOT     22
`define ALU_MULT    23
`define ALU_DIV     24
