+incdir+./cpu/cpu_pipeline
+incdir+./cpu/utils
+incdir+./cpu/other_modules/adder_32bit
+incdir+./cpu/control_unit_module
+incdir+./cpu/alu_module
+incdir+./cpu/pipeline_reg_modules/MEM_WB_pipeline_reg_module
+incdir+./cpu/other_modules/register_32bit
+incdir+./cpu/forwarding_unit_module
+incdir+./cpu/instruction_cache_module
+incdir+./cpu/pipeline_reg_modules/IF_ID_pipeline_reg_module
+incdir+./cpu/data_cache_module
+incdir+./cpu/cpu_single_cycle
+incdir+./cpu/other_modules/mux_2x1_32bit
+incdir+./cpu/pipeline_reg_modules/ID_EX_pipeline_reg_module
+incdir+./cpu/bj_detect_module
+incdir+./cpu/instruction_memory_module
+incdir+./cpu/immediate_gen_module
+incdir+./cpu/data_memory_module
+incdir+./cpu/reg_file_module
+incdir+./cpu/pipeline_reg_modules/EX_MEM_pipeline_reg_module
+incdir+./cpu/other_modules/mux_4x1_32bit
./cpu/utils/encodings.v
./cpu/other_modules/mux_4x1_32bit/mux_4x1_32bit.v
./cpu/other_modules/mux_2x1_32bit/mux_2x1_32bit.v
./cpu/other_modules/register_32bit/register_32bit.v
./cpu/other_modules/adder_32bit/adder_32bit.v
./cpu/control_unit_module/control_unit.v
./cpu/immediate_gen_module/immediate_generate.v
./cpu/data_memory_module/data_memory.v
./cpu/cpu_single_cycle/cpu_single_cycle.v
./cpu/forwarding_unit_module/forwarding_unit.v
./cpu/alu_module/alu.v
./cpu/instruction_memory_module/instruction_memory.v
./cpu/pipeline_reg_modules/MEM_WB_pipeline_reg_module/mem_wb_pipeline_reg.v
./cpu/pipeline_reg_modules/IF_ID_pipeline_reg_module/if_id_pipeline_reg.v
./cpu/pipeline_reg_modules/EX_MEM_pipeline_reg_module/ex_mem_pipeline_reg.v
./cpu/pipeline_reg_modules/ID_EX_pipeline_reg_module/id_ex_pipeline_reg.v
./cpu/bj_detect_module/bj_detect.v
./cpu/data_cache_module/data_cache.v
./cpu/reg_file_module/reg_file.v
./cpu/instruction_cache_module/instruction_cache.v
./cpu/cpu_pipeline/cpu_pipeline.v
