+incdir+./src
./src/WB.v
./src/ID_EX.v
./src/Parametric_decoder.v
./src/RCA.v
./src/Branch_predictor.v
./src/HA.v
./src/IMM_decoder.v
./src/shifter.v
./src/CSA.v
./src/MEM_WB.v
./src/Datapath.v
./src/logical_unit.v
./src/ID.v
./src/arithmetic_unit.v
./src/EX_MEM.v
./src/Single_cycle_processor.v
./src/D_FF_block.v
./src/ES_IMM_Decoder.v
./src/Branch_Controller.v
./src/MEM.v
./src/D_FF_async_rst.v
./src/TOP_Pipelined_design.v
./src/Instruction_decoder.v
./src/Controller.v
./src/Parametric_mux.v
./src/FA.v
./src/new_DFF.v
./src/RegisterFile.v
./src/Hazard_Detection.v
./src/Zero_comparator.v
./src/data_organizer.v
./src/new_DFF_block.v
./src/Data_Forward.v
./src/EX.v
./src/PC_new.v
./src/IF.v
./src/PC.v
./src/ALU.v
./src/IF_ID.v
./src/FU.v
