+incdir+./
./addsub.v
./DFlipFlop.v
./branching_MUX.v
./Stall_unit.v
./BCD.v
./branchAdder.v
./FWunit.v
./Imm_Gen.v
./shifter.v
./n_bit_reg.v
./Four_Digit_Seven_Segment_Driver.v
./defines.v
./threebyone_MUX.v
./memory.v
./fourbyone_MUX.v
./comparator.v
./mux2x1_8bits.v
./mux_2x1.v
./processor.v
./twobyoneMUX.v
./prv32_ALU.v
./ALU_Control_Unit.v
./RISCV_Pipeline.v
./full_adder.v
./reg_32bit.v
./UART_reciever_switch.v
./UART_receiver_multiple_keys.v
./reg_file.v
./control_unit.v
./PC.v
