+incdir+./RTL
./RTL/DataPath_Control.v
./RTL/Buffer.v
./RTL/ALU_Control.v
./RTL/Counter.v
./RTL/uart_tx.v
./RTL/DataPath.v
./RTL/Register_File.v
./RTL/Inst_mem.v
./RTL/Data_mem.v
./RTL/RAM.v
./RTL/Sign_extend.v
./RTL/Risc_V.v
./RTL/uart_top.v
./RTL/Control_Unit.v
./RTL/PC.v
./RTL/Mux2to1.v
./RTL/ALU.v
