+incdir+./GRU
+incdir+./DPLRV32zfh
+incdir+./DLPRV32
./GRU/gruMain.v
./GRU/sync.v
./GRU/fixedMul.v
./GRU/tanh.v
./GRU/sigmoid.v
./GRU/fixedAdd.v
./GRU/mac.v
./DPLRV32zfh/r32zfh.v
./DLPRV32/reg_of_decoder.v
./DLPRV32/logical.v
./DLPRV32/RISCV32.v
./DLPRV32/fetch.v
./DLPRV32/shift.v
./DLPRV32/reg_of_fetch.v
./DLPRV32/code_memory.v
./DLPRV32/add_sub.v
./DLPRV32/decoder.v
