+incdir+./lab1
+incdir+./lab0/part2
+incdir+./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new
+incdir+./lab0/part1
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/SevenSegMux.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/Register.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/uart_tx.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/DebugSevenSegment.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/PipelineCPU.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/InstructionMemory.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/DataMemory.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/cpu_top.v
./COCPU/COCPU_mimas/COCPU_mimas.srcs/sources_1/new/LUTRAM.v
./lab1/ShiftLeftOne.v
./lab1/Register.v
./lab1/ImmGen.v
./lab1/SingleCycleCPU.v
./lab1/ALUCtrl.v
./lab1/InstructionMemory.v
./lab1/Adder.v
./lab1/DataMemory.v
./lab1/Control.v
./lab1/PC.v
./lab1/Mux2to1.v
./lab1/ALU.v
./lab0/part2/alu.v
./lab0/part1/fullAdder.v
