+incdir+./code/Verilog/Display
+incdir+./code/Verilog/Control
+incdir+./code/Verilog/ALU
+incdir+./code/Verilog/Extend
+incdir+./code/Verilog/CPU
+incdir+./code/Verilog/Shift
+incdir+./code/Verilog/Memory
+incdir+./code/Verilog/Mux
./code/Verilog/Control/arithmetic_controller.v
./code/Verilog/Control/control_signal_controlle.v
./code/Verilog/Control/hard_wire_controller.v
./code/Verilog/ALU/ALU.v
./code/Verilog/Extend/extender_sign.v
./code/Verilog/Extend/extender_0.v
./code/Verilog/CPU/CPU_RISCV.v
./code/Verilog/Memory/RegFile.v
./code/Verilog/Memory/register.v
./code/Verilog/Memory/MEM.v
./code/Verilog/Memory/ROM.v
./code/Verilog/Shift/ari_shifter_right.v
./code/Verilog/Shift/log_shifter_left.v
./code/Verilog/Shift/log_shifter_right.v
./code/Verilog/Display/display_sel.v
./code/Verilog/Display/BinToBCD.v
./code/Verilog/Display/divider.v
./code/Verilog/Display/counter.v
./code/Verilog/Display/pattern.v
./code/Verilog/Display/decoder3_8.v
./code/Verilog/Display/counter_32.v
./code/Verilog/Mux/decoder2_4.v
./code/Verilog/Mux/mux2.v
./code/Verilog/Mux/mux4.v
./code/Verilog/Mux/mux32.v
